package Revision_Multithreading;

import java.io.FileWriter;
import java.util.LinkedList;
import java.util.Queue;
import java.util.UUID;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.ReentrantLock;

public class AsyncLogging {
    Queue<String> logQueue = new LinkedList<>();
    ReentrantLock lock = new ReentrantLock();
    Condition isEmpty = lock.newCondition();

    public AsyncLogging(){

        Thread runner = new Thread(()->{
            while (true) {
                lock.lock();
                try(FileWriter fileWriter = new FileWriter("logfile.log", true)) {
                    while (logQueue.size()==0) {
                        System.out.println("Logger thread is waiting as queue is empty......");
                        isEmpty.await();
                    }
                    String message = logQueue.poll();
                    System.out.println(message);
                    if(message!=null){
                        fileWriter.append(message+"\n") ;
                    }
                    fileWriter.flush();
                    fileWriter.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    lock.unlock();
                }
            }
        });
        runner.setDaemon(true);
        runner.start();
    }

    public void publishLog(String message){
        lock.lock();
        try {
            logQueue.add(message);
            isEmpty.signalAll();
        } catch (Exception e) {
            e.printStackTrace();
        } finally{ 
            lock.unlock();
        }
    }

    public static void main(String[] args) {
        AsyncLogging logger = new AsyncLogging();

        for(int i=1; i<=10; i++){
            Thread th = new Thread(()->{
                int id = (int) (Math.random()*100);
                String message = "Random message: "+ UUID.randomUUID().toString()+" with id:"+ id+" is generated by thread-"+Thread.currentThread().getName() ;
                logger.publishLog(message);
                
            });
            th.start();

            try {
                Thread.sleep((long) (Math.random()*1000));
            } catch (InterruptedException e) {
                e.printStackTrace();
            }        
        }

        try {
            Thread.sleep(30000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
